name: flutter-gallery
adopt-info: flutter-gallery
summary: Flutter Gallery
description: |
  A demo app for Flutter's material design and cupertino widgets, as well as many other features of the Flutter SDK.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

slots:
  # for GtkApplication registration
  flutter-gallery:
    interface: dbus
    bus: session
    name: io.flutter.demo.gallery

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/flutter_gallery

  flutter-gallery:
    command-chain:
      - bin/wayland-launch
    command: bin/flutter_gallery
    extensions: [flutter-master]
    environment:
     GDK_BACKEND: wayland
    plugs:
      - opengl
      - wayland
      - network

parts:
  flutter-gallery:
    source: https://github.com/flutter/gallery.git
    source-commit: dcf5088e5e3d0157d8a4d5d947cd7202ca19c941
    plugin: flutter
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl pulseaudio wayland
    stage-packages:
      - inotify-tools