name: flutter-gallery
adopt-info: flutter-gallery
summary: Flutter Gallery
description: |
  A demo app for Flutter's material design and cupertino widgets, as well as many other features of the Flutter SDK.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

slots:
  # for GtkApplication registration
  flutter-gallery:
    interface: dbus
    bus: session
    name: io.flutter.demo.gallery

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - snap/command-chain/desktop-launch
      - bin/run-daemon
      - env-setup
    command: bin/x11_kiosk_launch bin/flutter_gallery
    plugs:
      - opengl
      - wayland
      - network
      - network-bind

  flutter-gallery:
    command: bin/flutter_gallery
    extensions: [flutter-master]
    plugs:
      - opengl
      - network

parts:
  flutter-gallery:
    source: https://github.com/flutter/gallery.git
    source-commit: dcf5088e5e3d0157d8a4d5d947cd7202ca19c941
    plugin: flutter
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
    stage-packages:
      - inotify-tools

  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl pull

  mir-kiosk-x11:
    after: [ppa-setup]
    plugin: cmake
    source: https://github.com/MirServer/mir_kiosk_x11.git
    override-pull: |
      snapcraftctl pull
      server_version=`git rev-list --count HEAD`
      mir_version=`LANG=C apt-cache policy libmircommon-dev | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      snapcraftctl set-version $server_version-mir$mir_version
    build-packages:
      - pkg-config
      - libmiral-dev
      - make
      - g++
    stage-packages:
      - inotify-tools
      - libmiral4
      - try: [mir-platform-graphics-wayland]  # Mir 2.2+
      - else: [mir-platform-graphics-wayland18] # Mir < 2.2
      - dmz-cursor-theme
      - fonts-freefont-ttf
      - xwayland
      - libbz2-1.0
    prime:
    - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libGL.*
    - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libGL_*
    - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libEGL*
    - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libdrm*
    - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
    - -usr/share/doc

  env-setup:
    plugin: dump
    source: env-setup
    override-build: |
      snapcraftctl build
      sed s/\$\{SNAPCRAFT_ARCH_TRIPLET}/${SNAPCRAFT_ARCH_TRIPLET}/g --in-place $SNAPCRAFT_PART_INSTALL/hacks/*

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
