name: flutter-gallery
adopt-info: flutter-gallery
summary: Flutter Gallery
description: |
  A demo app for Flutter's material design and cupertino widgets, as well as many other features of the Flutter SDK.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

slots:
  # for GtkApplication registration
  flutter-gallery:
    interface: dbus
    bus: session
    name: io.flutter.demo.gallery

apps:
  flutter-gallery:
    command: bin/flutter_gallery
    extensions: [flutter-master]
    plugs:
      - opengl

parts:
  flutter-gallery:
    source: https://github.com/flutter/gallery.git
    plugin: flutter
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
